// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byrmeilhxmgcrissncba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5cm1laWxoeG1nY3Jpc3NuY2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTQxNDQsImV4cCI6MjA2NTU3MDE0NH0.O9bUDrXkT55lYkyXwiUgXkCBppqJ51hYoPgZRV0nvxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);